# Generated by Django 3.0.5 on 2020-04-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20200422_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
