# Generated by Django 3.0.5 on 2020-04-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20200427_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
