# Generated by Django 3.0.5 on 2020-04-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20200422_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
