# Generated by Django 3.0.5 on 2020-04-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_delete_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(default='admin', max_length=255),
            preserve_default=False,
        ),
    ]
